# https://docs.gradle.org/current/userguide/version_catalogs.html#sec::toml-dependencies-format

[versions]
spring-boot = "4.1.0"

[libraries]
spring-boot-starter = {module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot"}
spring-boot-starter-test = {module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot"}